clc;
close all;
clear all;

% Where are the CSVs generated by the maximum dispersion sweep
% Maximum dispersion value sweep range. 
MAXDISPSWEEP = 50:1:300;
CSVDIR = "/home/ariela/Workspace/Viewmind/CSVReadingMaxDispSweep/set_150_3";
% All files in the CSVDIR should be named like this followed by -MAXDISPVALUE.csv
FILE_BASE_NAME = "reading_es_2_2019_06_13_19_21";
fixation_duration_analisis(CSVDIR,FILE_BASE_NAME,MAXDISPSWEEP)
ylim([0,300])
xlim([150,300])

% Maximum dispersion value sweep range. 
MAXDISPSWEEP = 50:1:150;
CSVDIR = "/home/ariela/Workspace/Viewmind/CSVReadingMaxDispSweep/set_120_1";
FILE_BASE_NAME = "reading_es_2_2020_02_13_11_08"
fixation_duration_analisis(CSVDIR,FILE_BASE_NAME,MAXDISPSWEEP)