DROP USER IF EXISTS 'srvc_eye_db_manager'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'srvc_eye_db_manager'@'localhost' IDENTIFIED BY '2!PL0iJ34YK@0c%!ls0d';
DROP USER IF EXISTS 'srvc_dashboard'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'srvc_dashboard'@'localhost' IDENTIFIED BY 'Fh&2Q@9jO!X668%7twtT';
DROP USER IF EXISTS 'srvc_eye_db_manager'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'srvc_eye_db_manager'@'localhost' IDENTIFIED BY '2!PL0iJ34YK@0c%!ls0d';
DROP USER IF EXISTS 'srvc_dashboard'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'srvc_dashboard'@'localhost' IDENTIFIED BY 'Fh&2Q@9jO!X668%7twtT';
DROP USER IF EXISTS 'srvc_rawdata_server'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'srvc_rawdata_server'@'localhost' IDENTIFIED BY '_VBg55!WjIh=3700tdI?';
DROP USER IF EXISTS 'srvc_eye_db_manager'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'srvc_eye_db_manager'@'localhost' IDENTIFIED BY '2!PL0iJ34YK@0c%!ls0d';
DROP USER IF EXISTS 'srvc_rawdata_server'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'srvc_rawdata_server'@'localhost' IDENTIFIED BY '_VBg55!WjIh=3700tdI?';
DROP USER IF EXISTS 'srvc_eye_db_manager'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'srvc_eye_db_manager'@'localhost' IDENTIFIED BY '2!PL0iJ34YK@0c%!ls0d';
DROP USER IF EXISTS 'srvc_rawdata_server'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'srvc_rawdata_server'@'localhost' IDENTIFIED BY '_VBg55!WjIh=3700tdI?';
GRANT SELECT ON viewmind_dashboard.tEvaluations TO 'srvc_eye_db_manager'@'localhost';
GRANT SELECT ON viewmind_dashboard.tInstitutions TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT,SELECT ON viewmind_dashboard.tComplaints TO 'srvc_dashboard'@'localhost';
GRANT INSERT,SELECT,UPDATE ON viewmind_dashboard.tMonthCounters TO 'srvc_dashboard'@'localhost';
GRANT INSERT,SELECT ON viewmind_dashboard.tProduction TO 'srvc_dashboard'@'localhost';
GRANT INSERT,SELECT ON viewmind_dashboard.tPurchases TO 'srvc_dashboard'@'localhost';
GRANT INSERT,SELECT ON viewmind_dashboard.tStrings TO 'srvc_dashboard'@'localhost';
GRANT INSERT,SELECT ON viewmind_dashboard.tSuppliers TO 'srvc_dashboard'@'localhost';
GRANT INSERT,SELECT ON viewmind_dashboard.tTechnicalAssistance TO 'srvc_dashboard'@'localhost';
GRANT INSERT,SELECT ON viewmind_dashboard.tTrainedUsers TO 'srvc_dashboard'@'localhost';
GRANT INSERT,SELECT,UPDATE ON viewmind_dashboard.tUsers TO 'srvc_dashboard'@'localhost';
GRANT SELECT,INSERT,UPDATE ON viewmind_dashboard.tEvaluations TO 'srvc_dashboard'@'localhost';
GRANT SELECT,INSERT,UPDATE ON viewmind_dashboard.tInstitutions TO 'srvc_dashboard'@'localhost';
GRANT INSERT,SELECT ON viewmind_data.tDoctors TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT,SELECT ON viewmind_data.tEyeResults TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT ON viewmind_data.tFData TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT,SELECT ON viewmind_data.tPerformance TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT,SELECT ON viewmind_data.tResultsBinding TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT,SELECT ON viewmind_data.tResultsGoNoGo TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT,SELECT ON viewmind_data.tResultsNBackRT TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT,SELECT ON viewmind_data.tResultsReading TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT ON viewmind_data.tStudiesInReport TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT,SELECT ON viewmind_data.tDoctors TO 'srvc_dashboard'@'localhost';
GRANT SELECT ON viewmind_data.tEyeResults TO 'srvc_dashboard'@'localhost';
GRANT SELECT ON viewmind_data.tFData TO 'srvc_dashboard'@'localhost';
GRANT SELECT ON viewmind_data.tPerformance TO 'srvc_dashboard'@'localhost';
GRANT SELECT ON viewmind_data.tResultsBinding TO 'srvc_dashboard'@'localhost';
GRANT SELECT ON viewmind_data.tResultsGoNoGo TO 'srvc_dashboard'@'localhost';
GRANT SELECT ON viewmind_data.tResultsNBackRT TO 'srvc_dashboard'@'localhost';
GRANT SELECT ON viewmind_data.tResultsReading TO 'srvc_dashboard'@'localhost';
GRANT SELECT ON viewmind_data.tStudiesInReport TO 'srvc_dashboard'@'localhost';
GRANT SELECT ON viewmind_data.tDoctors TO 'srvc_rawdata_server'@'localhost';
GRANT SELECT ON viewmind_data.tEyeResults TO 'srvc_rawdata_server'@'localhost';
GRANT SELECT ON viewmind_data.tFData TO 'srvc_rawdata_server'@'localhost';
GRANT SELECT ON viewmind_data.tPerformance TO 'srvc_rawdata_server'@'localhost';
GRANT SELECT ON viewmind_data.tResultsBinding TO 'srvc_rawdata_server'@'localhost';
GRANT SELECT ON viewmind_data.tResultsGoNoGo TO 'srvc_rawdata_server'@'localhost';
GRANT SELECT ON viewmind_data.tResultsNBackRT TO 'srvc_rawdata_server'@'localhost';
GRANT SELECT ON viewmind_data.tResultsReading TO 'srvc_rawdata_server'@'localhost';
GRANT SELECT ON viewmind_data.tStudiesInReport TO 'srvc_rawdata_server'@'localhost';
GRANT INSERT ON viewmind_patdata.tMedicalRecords TO 'srvc_eye_db_manager'@'localhost';
GRANT INSERT ON viewmind_patdata.tPatientData TO 'srvc_eye_db_manager'@'localhost';
GRANT SELECT ON viewmind_patdata.tMedicalRecords TO 'srvc_rawdata_server'@'localhost';
GRANT SELECT ON viewmind_patdata.tPatientData TO 'srvc_rawdata_server'@'localhost';
GRANT INSERT ON viewmind_id.tPatientIDs TO 'srvc_eye_db_manager'@'localhost';
GRANT SELECT ON viewmind_id.tPatientIDs TO 'srvc_rawdata_server'@'localhost';
