var REPORT_REFERENCE = 
{
    "en": {
        "results": "RESULTS",
        "motto": "Cognitive Performance|Evaluations through|Eye-Tracking",
        "color_into": "The result of each function analyzed, is stated in the following code",
        "index_blue": "Function above|average",
        "index_green": "No relevant functional|problems|were detected",
        "index_yellow": "Midly deficient|functioning, not|necessarily pathological",
        "index_red": "Completely deficient|and\/or|pathological functioning",
        "patient": "NAME",
        "age": "AGE",
        "date": "DATE",
        "reqdr": "REQUESTING DOCTOR"
    },
    "es": {
        "results": "RESULTADOS",
        "motto": "Medición de Desempeño|Cognitivo mediante|Eye-Tracking",
        "color_into": "Para cada función analizada, el resultado se indica según el siguiente código:",
        "index_blue": "Funcionamiento|superior a|la media",
        "index_green": "No se han detectado|problemas|de funcionamiento relevante",
        "index_yellow": "Funcionamiento|levemente deficiente,|no necesariamente patológico",
        "index_red": "Funcionamiento|completamente|deficiente y\/o patológico",
        "patient": "NOMBRE",
        "age": "EDAD",
        "date": "FECHA",
        "reqdr": "MÉDICO SOLICITANTE"
    },
    "Binding": {
        "study_title_en": "COLORS",
        "study_title_es": "COLORES",
        "04_binding_index_2": {
            "title_en": "INDEX OF AMYLOID BETA PROTEIN CORRELATION",
            "title_es": "ÍNDICE DE DEPÓSITO BETA AMILOIDE",
            "explanation_en": "Locus Coeruleus and Superior colliculus|Entorhinal and Perirhinal Cortex. Medial Temporal Lobe",
            "explanation_es": "Locus Coeruleus y Coliculo superior.Corteza|Entorrinal y Perirrinal. Lobulo Temporal Medio",
            "range_text_en": "Normal value GREATER than 67",
            "range_text_es": "Valor normal MAYOR a 67",
            "cutoff_values": "0|67|134",
            "smaller_better": "false",
            "associated_value": "binding_conversion_index",
            "mult_by_100": "true"
        },
        "05_binding_index_3": {
            "title_en": "INDEX OF AMYLOID BETA PROTEIN CORRELATION",
            "title_es": "ÍNDICE DE DEPÓSITO BETA AMILOIDE",
            "explanation_en": "Locus Coeruleus and Superior colliculus|Entorhinal and Perirhinal Cortex. Medial Temporal Lobe",
            "explanation_es": "Locus Coeruleus y Coliculo superior. Corteza|Entorrinal y Perirrinal. Lobulo Temporal Medio",
            "range_text_en": "Normal value GREATER than 62",
            "range_text_es": "Valor normal MAYOR a 62",
            "cutoff_values": "0|62|124",
            "smaller_better": "false",
            "associated_value": "binding_conversion_index",
            "mult_by_100": "true"
        },
        "06_behavioral_conduct": {
            "title_en": "BEHAVIOURAL RESPONSE",
            "title_es": "RESPUESTA CONDUCTUAL",
            "explanation_en": "Entorhinal and Perirhinal Cortex.|Medial Temporal Lobe",
            "explanation_es": "Corteza Entorrinal y Perirrinal.|Lobulo Temporal Medio",
            "range_text_en": "Normal value GREATER than 22",
            "range_text_es": "Valor normal MAYOR a 22",
            "cutoff_values": "0|22|44",
            "smaller_better": "false",
            "associated_value": "behavioural_response",
            "mult_by_100": "false"
        }
    },
    "Go No-Go": {
        "study_title_en": "GO\\NO GO",
        "study_title_es": "GO\\NO GO",
        "14_gng_dmt_facilitate": {
            "title_en": "FACILITATED TASK TIME",
            "title_es": "TIEMPO EN TAREA FACILITADA",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value LESS than 710.6",
            "range_text_es": "Valor normal MENOR a 710.6",
            "cutoff_values": "593|710.6|828.2|945.8",
            "smaller_better": "true",
            "associated_value": "gonogo_dmt_facilitate",
            "mult_by_100": "false",
            "round_for_display": "false"
        },
        "15_gng_dmt_interference": {
            "title_en": "INTERFERENCE TASK TIME",
            "title_es": "TIEMPO EN TAREA CON INTERFERENCIA",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value LESS than 695.5",
            "range_text_es": "Valor normal MENOR a 695.5",
            "cutoff_values": "607|695.5|784|872.5",
            "smaller_better": "true",
            "associated_value": "gonogo_dmt_interference",
            "mult_by_100": "false",
            "round_for_display": "false"
        },
        "16_gng_pip_facilitate": {
            "title_en": "FACILITATED TASK INDEX",
            "title_es": "ÍNDICE DE TAREA FACILITADA",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value LESS than 0.11",
            "range_text_es": "Valor normal MENOR a 0.11",
            "cutoff_values": "0.07|0.11|0.15|0.19",
            "smaller_better": "true",
            "associated_value": "gonogo_pip_facilitate",
            "round_for_display": "false",
            "mult_by_100": "false"
        },
        "17_gng_pip_interference": {
            "title_en": "INTERFERENCE TASK INDEX",
            "title_es": "INDICE DE TAREA CON INTERFERENCIA",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value LESS than 0.23",
            "range_text_es": "Valor normal MENOR a 0.23",
            "cutoff_values": "0.15|0.23|0.31|0.39",
            "smaller_better": "true",
            "associated_value": "gonogo_pip_interference",
            "mult_by_100": "false",
            "round_for_display": "false"
        },
        "18_gng_speed_processing": {
            "title_en": "PROCESSING SPEED",
            "title_es": "VELOCIDAD DE PROCESAMIENTO",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value LESS than 1.76",
            "range_text_es": "Valor normal MENOR a 1.76",
            "cutoff_values": "1.68|1.76|1.84|1.92",
            "smaller_better": "true",
            "associated_value": "gonogo_speed_processing",
            "mult_by_100": "false",
            "round_for_display": "false"
        }
    },
    "NBackRT": {
        "study_title_en": "NBACK RT",
        "study_title_es": "NBACK RT",
        "07_nbackrt_num_fix_enc": {
            "title_en": "ENCODING EFFICIENCY",
            "title_es": "EFICIENCIA EN CODIFICACIÓN",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value LESS than 300",
            "range_text_es": "Valor normal MENOR a 300",
            "cutoff_values": "220|260|300|430|470",
            "smaller_better": "true",
            "associated_value": "number_of_fixations_enc",
            "mult_by_100": "false"
        },
        "08_nbackrt_num_fix_ret": {
            "title_en": "DECODING EFFICIENCY",
            "title_es": "EFICIENCIA EN DECODIFICACIÓN",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value LESS than 650",
            "range_text_es": "Valor normal MENOR a 650",
            "cutoff_values": "350|500|650|990|1330",
            "smaller_better": "true",
            "associated_value": "number_of_fixations_ret",
            "mult_by_100": "false"
        },
        "09_nbackrt_inhib_proc": {
            "title_en": "INHIBITORY PROCESSES",
            "title_es": "PROCESOS INHIBITORIOS",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value LESS than 18",
            "range_text_es": "Valor normal MENOR a 18",
            "cutoff_values": "0|3|18|45|60",
            "smaller_better": "true",
            "associated_value": "inhibitory_problems_percent",
            "mult_by_100": "false"
        },
        "10_nbackrt_seq_complete": {
            "title_en": "SEQUENCE COMPLETION",
            "title_es": "SECUENCIAS COMPLETAS",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value GREATER than 58",
            "range_text_es": "Valor normal MAYOR a 58",
            "cutoff_values": "32|45|58|76|94",
            "smaller_better": "false",
            "associated_value": "correct_complete_sequence_percent",
            "mult_by_100": "false"
        },
        "11_nbackrt_target_hit": {
            "title_en": "TARGET HIT",
            "title_es": "ACIERTOS A OBJETIVOS",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value GREATER than 60",
            "range_text_es": "Valor normal MAYOR a 60",
            "cutoff_values": "40|50|60|81|100",
            "smaller_better": "false",
            "associated_value": "correct_target_hit_percent",
            "mult_by_100": "false"
        },
        "12_nbackrt_mean_resp_time": {
            "title_en": "MEAN RESPONSE TIME",
            "title_es": "TIEMPO DE RESPUETA PROMEDIO",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value LESS than 2400",
            "range_text_es": "Valor normal MENOR a 2400",
            "cutoff_values": "800|1600|2400|2700|3000",
            "smaller_better": "true",
            "associated_value": "mean_response_time",
            "mult_by_100": "false"
        },
        "13_nbackrt_mean_sac_amp": {
            "title_en": "VISUAL EXPLORATION EFFICIENCY",
            "title_es": "EFICIENCIA EN EXPLORACIÓN VISUAL",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value GREATER than 4.1",
            "range_text_es": "Valor normal MAYOR a 4.1",
            "cutoff_values": "1.9|2.9|4|6|8",
            "smaller_better": "false",
            "associated_value": "mean_saccade_amplitude",
            "mult_by_100": "false"
        }
    },
    "Reading": {
        "study_title_en": "READING",
        "study_title_es": "LECTURA",
        "00_index_of_cognitive_impairment": {
            "title_en": "INDEX OF COGNITIVE IMPAIRMENT",
            "title_es": "ÍNDICE DE DETERIORO COGNITIVO",
            "explanation_en": "",
            "explanation_es": "",
            "range_text_en": "Normal value GREATER than 48",
            "range_text_es": "Valor normal MAYOR a 48",
            "cutoff_values": "0|48|96",
            "smaller_better": "false",
            "associated_value": "reading_predicted_deterioration",
            "mult_by_100": "true"
        },
        "01_executive_processes": {
            "title_en": "EXECUTIVE PROCESSES",
            "title_es": "PROCESOS EJECUTIVOS",
            "explanation_en": "Anterior cingulate cortex",
            "explanation_es": "Cortex del Cingulo Anterior",
            "range_text_en": "Normal value LOWER than 36",
            "range_text_es": "Valor normal MENOR a 36",
            "cutoff_values": "28|36|44|51",
            "smaller_better": "true",
            "associated_value": "executive_proceseses",
            "mult_by_100": "false"
        },
        "02_working_memory": {
            "title_en": "WORKING MEMORY",
            "title_es": "MEMORIA DE TRABAJO",
            "explanation_en": "Prefrontal cortex",
            "explanation_es": "Corteza Prefrontal",
            "range_text_en": "Normal value GREATER than 70",
            "range_text_es": "Valor normal MAYOR a 70",
            "cutoff_values": "50|60|70|80",
            "smaller_better": "false",
            "associated_value": "working_memory",
            "mult_by_100": "false"
        },
        "03_retrieval_memory": {
            "title_en": "RETRIEVAL MEMORY",
            "title_es": "MEMORIA DE RECUPERACIÓN",
            "explanation_en": "Dorsolateral prefrontal cortex.|Hippocampus,Subiculum",
            "explanation_es": "Corteza frontal Dorsolateral.|Hipocampo, Subiculum",
            "range_text_en": "Normal value GREATER than 8",
            "range_text_es": "Valor normal MAYOR a 8",
            "cutoff_values": "2|5|8|11",
            "smaller_better": "false",
            "associated_value": "retrieval_memory",
            "mult_by_100": "false"
        }
    }
}
