#!/bin/bash

# Constants to change in order to change compilation.
BASE_DIR="/home/ec2-user/viewmind_projects/VMTools"
SRC_DIR=$BASE_DIR"/LocalDBPrinter/src"
APPNAME="LocalDBPrinter"
OUTPUT=$BASE_DIR"/LocalDBPrinter/bin"
DEST="/home/ec2-user/LocalDBPrinter/"

# Changing the work directory.
echo "===================== CHANGING DIR TO: $OUTPUT ====================="
cd $OUTPUT

echo "===================== CLEANING ====================="
./clean

echo "===================== CALLIING QMAKE ====================="
qmake-qt5 $SRC_DIR -spec linux-g++
make qmake_all
if [[ -f "Makefile" ]]; then
   echo "===================== CALLIING MAKE ====================="
   make
   if [[ -f $APPNAME ]]; then
      mv $APPNAME $DEST
      echo "FINISHED"
   else
      echo "MAKE FAILED"
   fi
else
   echo "QMAKE FAILED"
fi

