import QtQuick 2.0

Item{
    /// TODO: CLEAN UP Most of these are not used.
    readonly property string vmCONFIG_PATIENT_DIRECTORY: "patient_directory"
    readonly property string vmCONFIG_DOCTOR_NAME: "doctor_name"
    readonly property string vmCONFIG_DOCTOR_EMAIL: "doctor_email"
    readonly property string vmCONFIG_DOCTOR_WORK_UID: "doctor_work_uid"
    readonly property string vmCONFIG_MOVING_WINDOW_DISP: "moving_window_max_dispersion"
    readonly property string vmCONFIG_MIN_FIXATION_LENGTH: "minimum_fixation_length"
    readonly property string vmCONFIG_SAMPLE_FREQUENCY: "sample_frequency"
    readonly property string vmCONFIG_DISTANCE_2_MONITOR: "distance_to_monitor"
    readonly property string vmCONFIG_XPX_2_MM: "x_px_mm"
    readonly property string vmCONFIG_YPX_2_MM: "y_px_mm"
    readonly property string vmCONFIG_LATENCY_ESCAPE_RAD: "latency_escape_radious"
    readonly property string vmCONFIG_MARGIN_TARGET_HIT: "margin_target_hit"
    readonly property string vmCONFIG_FAST_PROCESSING: "fast_processing"
    readonly property string vmCONFIG_EXP_LIST: "experiments"
    readonly property string vmCONFIG_OUTPUT_DIR: "output_directory"
    readonly property string vmCONFIG_RAW_DATA_REPO: "raw_data_repo"
    readonly property string vmCONFIG_READING_PX_TOL: "reading_px_tol_for_target"
    readonly property string vmCONFIG_EYEPROCESSOR_PATH: "eyeprocessor_path"
    readonly property string vmCONFIG_DUAL_MONITOR_MODE: "dual_monitor_mode"
    readonly property string vmCONFIG_OFFLINE_MODE: "offline_mode"
    readonly property string vmCONFIG_EXP_CONFIG_FILE: "exp_config_file"
    readonly property string vmCONFIG_DATA_OUTPUT_FILE: "data_output_file"
    readonly property string vmCONFIG_PATIENT_AGE: "patient_age"
    readonly property string vmCONFIG_PATIENT_NAME: "patient_name"
    readonly property string vmCONFIG_ADD_TO_REPORT: "add_to_report"
    readonly property string vmCONFIG_REPORT_LANGUAGE: "report_language"
    readonly property string vmCONFIG_PATIENT_EMAIL: "patient_email"
    readonly property string vmCONFIG_REPORT_NO_LOGO: "no_logo_in_report"
    readonly property string vmCONFIG_DEMO_MODE: "demo_mode"
    readonly property string vmCONFIG_BINDING_USE_NUMBERS: "binding_use_numbers"
    readonly property string vmCONFIG_BINDING_DEFAULT: "binding_default"
    readonly property string vmCONFIG_BC_FILE_FILTER: "bc_file_filter"
    readonly property string vmCONFIG_UC_FILE_FILTER: "uc_file_filter"
    readonly property string vmCONFIG_DAT_TIME_FILTER_THRESHOLD: "time_filter_threshold"
    readonly property string vmCONFIG_TCP_PORT: "tcp_port"
    readonly property string vmCONFIG_SERVER_ADDRESS: "server_address"
    readonly property string vmCONFIG_CONNECTION_TIMEOUT: "connection_time_out"
    readonly property string vmCONFIG_DATA_REQUEST_TIMEOUT: "data_request_time_out"
    readonly property string vmCONFIG_RUN_AND_QUIT: "run_and_quit"
    readonly property string vmCONFIG_NUMBER_OF_PARALLEL_PROCESSES: "number_of_paralell_processes"
    readonly property string vmCONFIG_WAIT_DATA_TIMEOUT: "wait_data_timeout"
    readonly property string vmCONFIG_RESOLUTION_WIDTH: "config_resolution_width"
    readonly property string vmCONFIG_RESOLUTION_HEIGHT: "config_resolution_height"
    readonly property string vmCONFIG_SELECTED_ET: "selected_eyetracker"
    readonly property string vmCONFIG_PATIENT_REPORT_DIR: "patient_report_dir"
    readonly property string vmCONFIG_REPORT_DATE: "report_date"
    readonly property string vmCONFIG_SSLSERVER_PATH: "ssl_server_path"
    readonly property string vmCONFIG_REPORT_PATH: "report_path"
    readonly property string vmCONFIG_RESULTS_ATTENTIONAL_PROCESSES: "attentional_processes"
    readonly property string vmCONFIG_RESULTS_EXECUTIVE_PROCESSES: "executive_proceseses"
    readonly property string vmCONFIG_RESULTS_WORKING_MEMORY: "working_memory"
    readonly property string vmCONFIG_RESULTS_RETRIEVAL_MEMORY: "retrieval_memory"
    readonly property string vmCONFIG_RESULTS_MEMORY_ENCODING: "memory_encoding"
    readonly property string vmCONFIG_VALID_EYE: "valid_eye"
    readonly property string vmCONFIG_P_EXP_FIELDING: "fielding"
    readonly property string vmCONFIG_P_EXP_BIDING_UC: "binding_uc"
    readonly property string vmCONFIG_P_EXP_BIDING_BC: "binding_bc"
    readonly property string vmCONFIG_P_EXP_READING: "reading"
    readonly property string vmCONFIG_P_EXP_PARKINSON: "parkinson"
    readonly property string vmCONFIG_P_LANG_ES: "Spanish"
    readonly property string vmCONFIG_P_LANG_EN: "English"
    readonly property string vmCONFIG_P_ET_MOUSE: "Mouse"
    readonly property string vmCONFIG_P_ET_REDM: "REDm"
    readonly property string vmCONFIG_P_ET_HTCVIVEEYEPRO: "HTCVIVEEyePro"
    readonly property string vmCONFIG_DOCTOR_UID : "doctor_uid"
    readonly property string vmCONFIG_PATIENT_UID: "patient_uid"
    readonly property string vmCONFIG_BINDING_TARGET_SMALL: "binding_target_small"
    readonly property string vmCONFIG_BINDING_NUMBER_OF_TARGETS:"binding_number_of_targets"
    readonly property string vmCONFIG_DEFAULT_COUNTRY:"default_country"
    readonly property string vmCONFIG_USE_MOUSE: "use_mouse"
    readonly property string vmCONFIG_READING_EXP_LANG: "reading_exp_lang"
    readonly property string vmCONFIG_PATIENT_DISPLAYID: "patient_displayid"
    readonly property string vmCONFIG_VR_ENABLED: "vr_enabled"
}
